INSERT INTO `secciones` (`nombre`, `abreviatura`, `estado`) VALUES
('ASESORIA LEGAL', 'AL', 1),
('TECNOLOGÍAS', 'STIC', 1),
('SIFDE', 'SIFDE', 1),
('SECCION DE PRUEBA', 'SP', 1),
('UNIDAD DE GEOGRAFIA  Y LOGISTICA  ELECTORAL', 'UGLE', 1),
('UNIDAD ADMINISTRATIVA  FINANCIERA', 'AF', 1),
('UNIDAD POA Y RECURSOS HUMANOS', 'PR', 1),
('ACTIVO FIJO Y CONTRATACIONES', 'AFC', 1),
('UNIDAD DE CONTABILIDAD', 'C', 1),
('UNIDAD DE ALMACENES Y SERV. GRALES.', 'ASG', 1),
('SALA PLENA', 'SP', 1),
('SECRETARIA DE CAMARA', 'SC', 1);
